application:
  locale: ru_RU

spring:
  messages:
    basename: "i18n/messages"
    encoding: "UTF-8"

test:
  file-name: tasks.csv
  passing-score: 60.0

bean:
  output: "#{T(java.lang.System).out}"
  input: "#{ T(java.lang.System).in}"